### ISSUE TITLE
[Request] update web site

### ISSUE THREAD

**Issue by blacky-i** [Project-MONAI/project-monai.github.io#56]
Good day everyone.

I have added our university bundle  to Project-MONAI/model-zoo#460 , want to ask you to update website, so information can appear on [website](https://monai.io/model-zoo.html). Or there are some guidelines to do so?

Thank you!

**Comment by wyli** [comment]
thanks @blacky-i, there's automatic weekly build process to update the website, but I just triggered manually so now the item is on the website. please feel free to reopen this if there's any concern.
